---

# Defaults file for openjdk-jre

openjdk_jre_package_state: 'present'

# Add more default version if user not define "openjdk_jre_version"
# Usefull because all distribution not have the same version
openjdk_jre_default_distribution_version:
  trusty: 7
  xenial: 9
openjdk_jre_default_version: "{{
  openjdk_jre_default_distribution_version[ansible_distribution_release]
  | default(7) }}"

openjdk_jre_version: "{{ openjdk_jre_default_version }}"
