---

- name: 'CONFIG | Manage directories permissions'
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner | default(elasticsearch_user_name) }}"
    group: "{{ item.group | default(elasticsearch_group_name) }}"
    mode: "{{ item.mode }}"
  notify: 'HANDLER | Restart elasticsearch'
  with_items: "{{ elasticsearch_dirs_paths }}"


- name: 'CONFIG | Generate main config file'
  template:
    src: "{{ role_path }}/templates/etc/elasticsearch.yml.j2"
    dest: "{{ elasticsearch_etc_dir_path }}/elasticsearch.yml"
    group: "{{ elasticsearch_user_name }}"
    owner: "{{ elasticsearch_group_name }}"
    mode: "{{ elasticsearch_config_files_mode }}"
  notify: 'HANDLER | Restart elasticsearch'


- name: 'CONFIG | Generate default config file'
  template:
    src: "{{ role_path }}/templates/etc/default.j2"
    dest: '/etc/default/elasticsearch'
    group: "{{ elasticsearch_user_name }}"
    owner: "{{ elasticsearch_group_name }}"
    mode: "{{ elasticsearch_config_files_mode }}"
  notify: 'HANDLER | Restart elasticsearch'


- name: 'CONFIG | Generate logrotate config file'
  template:
    src: "{{ role_path }}/templates/etc/logrotate.j2"
    dest: "{{ elasticsearch_logrotate_dir_path }}/elasticsearch"
    group: 'root'
    owner: 'root'
    mode: "{{ elasticsearch_config_files_mode }}"
  notify: 'HANDLER | Restart elasticsearch'


- name: 'CONFIG | LIMITS | Update elasticsearch limits'
  template:
    src: "{{ role_path }}/templates/etc/limits.conf.j2"
    dest: "{{ elasticsearch_limits_dir_path }}/elasticsearch.conf"
    group: "{{ elasticsearch_user_name }}"
    owner: "{{ elasticsearch_group_name }}"
    mode: "{{ elasticsearch_config_files_mode }}"
  notify: 'HANDLER | Restart elasticsearch'
