---

- name: 'Manage configuration directories'
  become: True
  file:
    path: "{{ elasticsearch_etc_default_conf_dir }}"
    state: 'directory'
    owner: "{{ elasticsearch_etc_folders_owner }}"
    group: "{{ elasticsearch_etc_folders_group }}"
    mode: "{{ elasticsearch_etc_folders_mode }}"
  notify:
    - 'restart elasticsearch'


- name: 'Manage data directories'
  become: True
  file:
    path: "{{ item }}"
    state: 'directory'
    owner: "{{ elasticsearch_data_folders_owner }}"
    group: "{{ elasticsearch_data_folders_group }}"
    mode: "{{ elasticsearch_data_folders_mode }}"
  with_items: "{{ elasticsearch_etc_default_data_dir }}"
  notify:
    - 'restart elasticsearch'


- name: 'Manage log directories'
  become: True
  file:
    path: "{{ elasticsearch_etc_default_log_dir }}"
    state: 'directory'
    owner: "{{ elasticsearch_log_folders_owner }}"
    group: "{{ elasticsearch_log_folders_group }}"
    mode: "{{ elasticsearch_log_folders_mode }}"
  notify:
    - 'restart elasticsearch'


- name: 'Generate main config file'
  become: True
  template:
    src: "{{ role_path }}/templates/etc/elasticsearch/elasticsearch.yml.j2"
    dest: "{{ elasticsearch_etc_default_conf_file }}"
    group: "{{ elasticsearch_etc_files_group }}"
    owner: "{{ elasticsearch_etc_files_owner }}"
    mode: "{{ elasticsearch_etc_files_mode }}"
  notify:
    - 'restart elasticsearch'


- name: 'Generate logging config file'
  become: True
  template:
    src: "{{ role_path }}/templates/etc/elasticsearch/logging.yml.j2"
    dest: "{{ elasticsearch_etc_default_conf_dir ~ '/logging.yml' }}"
    group: "{{ elasticsearch_etc_files_group }}"
    owner: "{{ elasticsearch_etc_files_owner }}"
    mode: "{{ elasticsearch_etc_files_mode }}"
  notify:
    - 'restart elasticsearch'


- name: 'Generate default config file'
  become: True
  template:
    src: "{{ role_path }}/templates/etc/default/elasticsearch.j2"
    dest: '/etc/default/elasticsearch'
    group: "{{ elasticsearch_etc_files_group }}"
    owner: "{{ elasticsearch_etc_files_owner }}"
    mode: "{{ elasticsearch_etc_files_mode }}"
  notify:
    - 'restart elasticsearch'


- name: 'Generate logrotate config file'
  become: True
  template:
    src: "{{ role_path }}/templates/etc/logrotate.d/elasticsearch.j2"
    dest: '/etc/logrotate.d/elasticsearch'
    group: 'root'
    owner: 'root'
    mode: "{{ elasticsearch_etc_files_mode }}"
  notify:
    - 'restart elasticsearch'


- name: 'Update elasticsearch limits'
  become: True
  template:
    src: "{{ role_path }}/templates/etc/security/limits.d/elasticsearch.conf.j2"
    dest: '/etc/security/limits.d/elasticsearch.conf'
    group: "{{ elasticsearch_etc_files_group }}"
    owner: "{{ elasticsearch_etc_files_owner }}"
    mode: "{{ elasticsearch_etc_files_mode }}"
  notify:
    - 'restart elasticsearch'


- name: 'Generate systemd service file'
  become: True
  template:
    src: "{{ role_path }}/templates/usr/lib/systemd/system/elasticsearch.service.j2"
    dest: '/usr/lib/systemd/system/elasticsearch.service'
    group: "{{ elasticsearch_etc_files_group }}"
    owner: "{{ elasticsearch_etc_files_owner }}"
    mode: "{{ elasticsearch_etc_files_mode }}"
  register: 'elasticsearch_systemd_config'
  notify:
    - 'restart elasticsearch'
  when: "{{ (ansible_distribution_release | lower) == 'xenial' }}"


- name: 'Reload systemd configuration'
  become: True
  command: '/bin/systemctl daemon-reload'
  when:
    - "{{ elasticsearch_systemd_config | changed }}"
    - "{{ (ansible_distribution_release | lower) == 'xenial' }}"


- name: 'Enable elasticsearch service on boot'
  become: True
  service:
    name: "{{ elasticsearch_service_name }}"
    enabled: "{{ elasticsearch_service_enabled }}"
    state: "{{ elasticsearch_service_state }}"
  failed_when: False
