---

- name: 'INSTALL | APT | Manage system dependencies'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
    cache_valid_time: "{{ elasticsearch_apt_cache_valid_time }}"
  with_items: "{{ elasticsearch_system_dependencies }}"


- name: 'INSTALL | APT | Install Elasticsearch GPG key'
  apt_key:
    url: 'https://packages.elastic.co/GPG-KEY-elasticsearch'
    state: 'present'


- name: 'INSTALL | APT | Add Elasticsearch repository'
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state | default('present') }}"
    filename: "{{ item.filename | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items: "{{ elasticsearch_repositories }}"


- name: 'INSTALL | APT | Install Elasticsearch packages'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
    cache_valid_time: "{{ elasticsearch_apt_cache_valid_time }}"
  with_items: "{{ elasticsearch_packages }}"
  notify:
    - 'HANDLER | Restart elasticsearch'


- name: 'INSTALL | SERVICE | Manage Elasticsearch service'
  service:
    name: "{{ elasticsearch_service_name }}"
    enabled: "{{ elasticsearch_service_enabled }}"
    state: "{{ elasticsearch_service_state }}"
  notify:
    - 'HANDLER | Restart elasticsearch'


- name: 'INSTALL | SYSCTL | Update virtual memory sysctl setting'
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
  with_items: "{{ elasticsearch_sysctl_rules }}"
