---

# Tasks file for elasticsearch

- name: 'Load the OS specific varibles'
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"
  tags:
    - 'elasticsearch::role'
    - 'elasticsearch::install'


- include: 'install_debian.yml'
  when: "{{ (ansible_os_family | lower) == 'debian' }}"
  tags:
    - 'elasticsearch::role'
    - 'elasticsearch::install'


- include: 'configure.yml'
  tags:
    - 'elasticsearch::role'
    - 'elasticsearch::config'
