---

# Handlers file for elasticsearch

- name: restart elasticsearch
  service:
    name  : "{{ elasticsearch_service_name }}"
    state : restarted
  when : elasticsearch_service_state != "stopped"
