---

# Handlers main file for elasticsearch role

- name: 'restart elasticsearch'
  become: True
  service:
    name: "{{ elasticsearch_service_name }}"
    state: 'restarted'
  when: "{{ elasticsearch_service_state != 'stopped' }}"
