---
galaxy_info:
  author: 'Alexandre Chaussier'
  description: 'Install openjdk-jre package'
  company: 'Infopen (http://infopen.pro)'
  license: 'MIT'
  min_ansible_version: '1.4'
  github_branch: 'master'
  platforms:
    - name: 'Ubuntu'
      versions:
        - 'precise'
        - 'quantal'
        - 'raring'
        - 'saucy'
        - 'trusty'
        - 'utopic'
        - 'vivid'
    - name: 'Debian'
      versions:
        - 'squeeze'
        - 'wheezy'
        - 'jessie'
  galaxy_tags:
    - 'development'
    - 'web'

dependencies: []
